style: indent with tabs instead of spaces

diff --git a/.github/hooks/pre-commit b/.github/hooks/pre-commit
--- a/.github/hooks/pre-commit
+++ b/.github/hooks/pre-commit
@@ -3,8 +3,8 @@
 [ -t 1 ] && exec < /dev/tty
 
 if git status --short | grep --quiet '^MM'; then
-  printf '%s\n' "ERROR: Some staged files have unstaged changes" >&2
-  exit 1;
+	printf '%s\n' "ERROR: Some staged files have unstaged changes" >&2
+	exit 1
 fi
 
 yarn biome check --write --staged --no-errors-on-unmatched
